name: Auto Update Cloudflare Vless Trojan Fork

on:
  # 每天凌晨2点运行
  schedule:
    - cron: "0 2 * * *"
  # 允许手动触发
  workflow_dispatch:

permissions:
  contents: write # 授予写入权限以允许推送更改

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出您的仓库
        uses: actions/checkout@v4
        with:
          # 使用 GITHUB_TOKEN 认证，允许推送
          token: ${{ secrets.GITHUB_TOKEN }}
          # 检查所有分支，以便拉取上游更改
          fetch-depth: 0

      - name: 配置 Git 用户
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 添加上游远程仓库
        run: |
          git remote add upstream https://github.com/yonggekkk/Cloudflare_vless_trojan.git || true
          # `|| true` 防止远程已存在时报错导致工作流失败

      - name: 获取上游更改
        run: |
          echo "Fetching upstream changes..."
          git fetch upstream

      - name: 合并上游更改到主分支
        run: |
          echo "Attempting to merge upstream/main into main..."
          # 尝试合并上游 main 分支到您的 main 分支
          # `--no-edit` 防止合并时出现交互式编辑信息
          # `--allow-unrelated-histories` 适用于两个独立仓库首次合并的情况，
          # 如果您的 fork 已经是从上游创建的，则可以移除此项。
          # 如果发生冲突，此命令将失败，Action 也会失败。
          git merge upstream/main --no-edit || { echo "Merge conflict detected! Action will fail. Please resolve manually."; exit 1; }

      - name: 推送更改到您的仓库
        run: |
          echo "Pushing changes to your repository..."
          git push origin main
          echo "Auto update completed successfully."
        # 如果上一步合并失败（冲突），则不会执行此步骤，因为默认情况下会跳过失败的步骤。
